name: Fonts Generation
on: 
  push:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  Generate-Fonts:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup Python environment
        uses: actions/setup-python@v5
        with:
            python-version: '3.12'
            architecture: 'x64'
            cache: 'pip'
            cache-dependency-path: ./requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt
      - name: Generate Fonts
        run: |
          set -o xtrace
          python wing-font.py -opt -i input_fonts/ChironSungHK-R.ttf -a input_fonts/NotoSerif-Regular.ttf -m mappings/canto-lshk.csv -o ChironSungHK-Noto-lshk -as 0.13
          python wing-font.py -opt -i input_fonts/ChironSungHK-R.ttf -a input_fonts/NotoSerif-Regular.ttf -m mappings/canto-yale.csv -o ChironSungHK-Noto-yale -as 0.13
          python wing-font.py -opt -i input_fonts/ChironSungHK-R.ttf -a input_fonts/NotoSerif-Regular.ttf -m mappings/canto-chishima.csv -o ChironSungHK-Noto-chishima -as 0.13
          python wing-font.py -opt -i input_fonts/ChironSungHK-R.ttf -a input_fonts/NotoSerif-Regular.ttf -m mappings/canto-guangdong.csv -o ChironSungHK-Noto-guangdong -as 0.13
          python wing-font.py -opt -i input_fonts/ChironSungHK-R.ttf -a input_fonts/NotoSerif-Regular.ttf -m mappings/canto-lau.csv -o ChironSungHK-Noto-lau -as 0.13
          python wing-font.py -i input_fonts/ChironSungHK-R.ttf -a input_fonts/ChironSungHK-R.ttf -m mappings/cangjie.csv -o ChironSungHK-cangjie -as 0.25
          python wing-font.py -opt -i input_fonts/ChironSungHK-R-It.ttf -a input_fonts/NotoSerif-Regular.ttf -m mappings/canto-lshk.csv -o ChironSungHK-Noto-lshk-It -as 0.13
          python wing-font.py -opt -i input_fonts/ChironSungHK-R-It.ttf -a input_fonts/NotoSerif-Regular.ttf -m mappings/canto-yale.csv -o ChironSungHK-Noto-yale-It -as 0.13
          python wing-font.py -opt -i input_fonts/ChironSungHK-R-It.ttf -a input_fonts/NotoSerif-Regular.ttf -m mappings/canto-chishima.csv -o ChironSungHK-Noto-chishima-It -as 0.13
          python wing-font.py -opt -i input_fonts/ChironSungHK-R-It.ttf -a input_fonts/NotoSerif-Regular.ttf -m mappings/canto-guangdong.csv -o ChironSungHK-Noto-guangdong-It -as 0.13
          python wing-font.py -opt -i input_fonts/ChironSungHK-R-It.ttf -a input_fonts/NotoSerif-Regular.ttf -m mappings/canto-lau.csv -o ChironSungHK-Noto-lau-It -as 0.13
          python wing-font.py -i input_fonts/ChironSungHK-R-It.ttf -a input_fonts/ChironSungHK-R-It.ttf -m mappings/cangjie.csv -o ChironSungHK-cangjie-It -as 0.25

      - name: create deployment folder
        run: mkdir -p fonts
      - name: cp files into deployment folder
        run: |
          cp \
          *.ttf \
          *.woff \
          CNAME \
          fonts/
      - name: Upload fonts
        uses: JamesIves/github-pages-deploy-action@v4
        with:
            folder: fonts
            commit-message: Update resources
            branch: gh-pages
            clean: true
